### ISSUE TITLE
Add tests for this package

### ISSUE THREAD

**Issue by mbad0la** [o-d-i-n/all-contributors-atom#2]
Tests go a long way in debugging updated code behaviour. Atom natively uses Jasmine. Please comment to be involved in resolving this issue.

**Comment by karanchahal** [comment]
I'm interested in resolving this. Can you point me some resources so that I can begin work on this ?

**Comment by mbad0la** [comment]
@karanchahal let's talk about this on Monday. Sorry for the late response.
